language: bash
sudo: required

env:
  - TYPE=php VARIANT=7.1-cli
  - TYPE=php VARIANT=7.1-cli-xdebug
  - TYPE=php VARIANT=7.1-fpm
  - TYPE=php VARIANT=7.1-fpm-xdebug
  - TYPE=nodejs VARIANT=9.11-yarn

services:
  - docker

install:
  - if [ -f ./${TYPE}/build/${VARIANT} ]; then `cat ./${TYPE}/build/${VARIANT}`; fi
  - docker build -t iwyg/${TYPE}:${VARIANT} -f ./${TYPE}/${VARIANT} ./${TYPE}

script:
  - ./${TYPE}/${TYPE}${VARIANT}-test
